### GET usuarios
GET http://localhost:1234/api/usuarios

### Registrar usuario
POST http://localhost:1234/api/auth/register
Content-Type: application/json

{
    "nombre": "Allison Lucia",
    "apellido": "Grados Gil",
    "email": "allison.grados@example.com",
    "password": "password1",
    "rol": "Administrador"
}

### GET api/auth
GET http://localhost:1234/api/auth
