import 'dotenv/config'

const {
  MODE,
  DB_HOST,
  DB_MYSQL_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  TOKEN_SECRET,
  CLIENT_URL_DEV,
  CLIENT_URL_PROD
} = process.env

const CLIENT_URL = (MODE && MODE === 'dev') ? CLIENT_URL_DEV : CLIENT_URL_PROD

export {
  DB_HOST,
  DB_MYSQL_PORT,
  DB_USER,
  DB_PASSWORD,
  DB_DATABASE,
  TOKEN_SECRET,
  CLIENT_URL
}
